server:
    port: 8080
spring:
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://192.168.195.150:3306/jframe
        username: root
        password: home


mybatis-plus:
    mapper-locations: classpath:/mapper/*.xml