server:
  port: 8080
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.195.150:3306/jframe
    username: root
    password: home
  redis:
    database: 0
    host: 192.168.195.150
    port: 6379
    # password :
    timeout: 5s
    connect-timeout: 5s
  cache:
    type: REDIS
    redis:
      time-to-live: 1h # 设置过期时间为 1 小时
management:
  endpoints:
    web:
      exposure:
        include=*:




mybatis-plus:
  mapper-locations: classpath:/mapper/*.xml

jframe:
  security:
    jwt:
      header: Authorization
      # 过期时间，s为单位 7d 60 * 60 * 24 * 7
      expire: 604800
      secret: jframe_jwt_jvciziyaebnr
